language: python
sudo: false
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  # Disabled until gRPC supports PyPy.
  # - python: pypy
  #   env: TOXENV=pypy
  - python: 3.5
    env: TOXENV=lint
  - python: 3.6
    env: TOXENV=docs
  - python: 3.6
    env: TOXENV=cover
cache:
  directories:
  - ${HOME}/.cache
install:
- pip install --upgrade tox
script: tox
after_success:
- test $TOXENV = "cover" && codecov
